### ISSUE TITLE
Request: User SemVer versioning

### ISSUE THREAD

**Issue by LovingMelody** [gposingway/gposingway#23]
Please use [SemVer](https://semver.org/) versioning to make the details of an update easier to read. Current versioning doesn't seem well defined and is difficult to make sense of.
Please refer to this blog post if you would like to know more about the benefits: https://www.elegantthemes.com/blog/wordpress/semantic-versioning

**Comment by LeonAquitaine** [comment]
This is a very good point, one that I considered myself as the project approached a release-ready state.

My current take is that GPosingway is a compilation where most of its components (shaders and presets) follow SemVer (or some variants of it), but the top-level project doesn't have a functionality of its own - rather, its objective is to provide a cohesive baseline. By that definition, there should never be a 'breaking change' to the project, just additive releases (in the form of, for example, a new community shader or a new preset collectin added to the project) so it would never leave the 1.*.* version.

Having no APIs and being based on a rapid iterations in a continuous delivery approach, I came to the conclusion that a simplified Release Number approach tied to expanding features would suffice (R3, R4 and so forth.)

Of course, this is up to discussion. SemVer is a powerful organizational tool for managing dependencies and communicating compatibility, but it's not a one-size-fits-all solution - and the current release schema is just my *initial* take. I may be missing something important though, so arguments in favor of SemVer are more than welcome.

**Comment by LovingMelody** [comment]
Thank you for considering adopting SemVer. While GPosingway itself might not introduce breaking changes, updates to ReShade or modifications in the dependency repository could potentially affect compatibility. Using SemVer for GPosingway versions can help assess whether the project is compatible with a pinned version of ReShade, especially in relation to other shaders. I believe it would be reasonable for the repository's major version to be incremented whenever the underlying ReShade version undergoes a major revision.

**Comment by LeonAquitaine** [comment]
Associated project topic marked as in progress as discovery on ReShade historical breaking changes are evaluated. This may lead to standard SemVer adoption.

**Comment by LeonAquitaine** [comment]
SemVer added to the roadmap for the GPosingway download manager project, while the shader contents of this repo is considered stable at this point. While it'll be closed as Not Planned, this issue certainly contributed to the decision for the tool.
